### ISSUE TITLE
Need more models support.

### ISSUE THREAD

**Issue by chrislee87** [asafschers/goscore#4]
Will models such as Logistic Regression be added? Or hints and suggestions on how to implement new models.

**Comment by asafschers** [comment]
Hey
I don't  plan adding Logistic Regression in the near future as I'm currently working on other projects.
I would be happy to help with implementation and code review - you can start by reading how regression PMMLs are designed here - http://dmg.org/pmml/v4-2-1/Regression.html
And how other models are implemented and tested in goscore.

Please contact me with any question you have
